Sprint2/step2
Canfus/stellar-burgers pull request #4
Opened 2023-02-25 13:57 UTC by Canfus

2023-02-26 05:28 UTC, andryxxa93 requested changes
Супер! Вы отлично поработали, осталось только два замечания:

- При скролле внутри компонента `BurgerIngredients` самый ближний к верхней левой границе заголовок контейнера должен становится активным
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

Пожалуйста не создавайте новый pull-request после каждой проверки - это лишнее действие для вас и усложнение проверки для ревьюера.

Удачи!

2023-02-26 09:18 UTC, Canfus commented
> * Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.
Прошу Вас обратить внимание, что содержимое хранилища приходит к начальному состоянию при каждом нажатии на кнопку `Оформить заказ`, по нажатии которой отправляется запрос на сервер, в это время в состоянии устанавливается статус `state.status = 'pending'` и в это время содержимое хранилища сбрасывается к начальному состоянию и при неожиданной ошибке, при повторном оформлении заказа вывод старого номера заказа невозможен.

2023-02-26 11:08 UTC, andryxxa93 commented
> > * Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.
> 
> Прошу Вас обратить внимание, что содержимое хранилища приходит к начальному состоянию при каждом нажатии на кнопку `Оформить заказ`, по нажатии которой отправляется запрос на сервер, в это время в состоянии устанавливается статус `state.status = 'pending'` и в это время содержимое хранилища сбрасывается к начальному состоянию и при неожиданной ошибке, при повторном оформлении заказа вывод старого номера заказа невозможен.

Да, всё верно, прошу прощения, не заметил этот механизм.

2023-02-27 06:31 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-02-27 06:33 UTC, merged