Sprint6/step1
Canfus/stellar-burgers pull request #8
Opened 2023-04-28 18:40 UTC by Canfus

Завершена работа над 6 спринтом

2023-04-28 18:54 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Для одной функции `it` используется один `expect` - это хорошая практика.
- Успешный деплой проекта.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Необходимо протестировать все слайсы
- Необходимо добавить команду запуска cypress в `package.json`
- Некоторые тесты cypress падают

<img width="510" alt="Снимок экрана 2023-04-28 в 21 53 36" src="https://user-images.githubusercontent.com/60173362/235230107-fbd4bf81-afba-46ca-b66b-19fca5f75326.png">


**Можно лучше**
- [test-id="constructor"] - встречается несколько раз - если селектор дублируется больше 2 раз, то желательн помещать их в селекторы константы, чтобы можно было легко изменить в случае необходимости.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-29 10:10 UTC, Canfus commented
> Необходимо исправить:
> 
> * Необходимо протестировать все слайсы

Обязательно ли покрывать тестами редюсеры, которые никак не влияют от входных данных?
К примеру такие редюсеры отвечают за показ/скрытие модальных окон:
```
openOrderDetails: (state) => {
  state.currentOrder.status = 'visible';
},
closeOrderDetails: (state) => {
  state.currentOrder.status = 'hidden';
}
```
Данные редюсеры не имеют входных данных и никак не зависят от них

2023-04-29 10:53 UTC, Canfus commented
> **Можно лучше**
> 
> * [test-id="constructor"] - встречается несколько раз - если селектор дублируется больше 2 раз, то желательн помещать их в селекторы константы, чтобы можно было легко изменить в случае необходимости.

Прошу Вас обратить внимание, `[test-id="constructor"]` вынесена как раз таки в селектор-константу на 58 строчке кода, для удобного использования в дальнейшем, см. на скрине ниже
![image](https://user-images.githubusercontent.com/37434920/235298856-bd5f80c0-e706-40f0-9a55-0eb7d8af5613.png)

2023-04-30 04:39 UTC, andryxxa93 commented
Супер! Cypress тесты теперь работают как надо!
Но остались две проблемы:

**Необходимо исправить**
- Слайл User.ts остался не протестирован.
- Необходимо добавить команду запуска cypress в package.json.

2023-04-30 04:40 UTC, andryxxa93 commented
> > Необходимо исправить:
> > 
> > * Необходимо протестировать все слайсы
> 
> Обязательно ли покрывать тестами редюсеры, которые никак не влияют от входных данных? К примеру такие редюсеры отвечают за показ/скрытие модальных окон:
> 
> ```
> openOrderDetails: (state) => {
>   state.currentOrder.status = 'visible';
> },
> closeOrderDetails: (state) => {
>   state.currentOrder.status = 'hidden';
> }
> ```
> 
> Данные редюсеры не имеют входных данных и никак не зависят от них

Такие простые редьюсеры тестировать не обязательно

2023-05-01 19:13 UTC, andryxxa93 commented
Супер! `Jest` тесты и `Cypress` настроены и работают верно. 
Работа принята. Удачи вам и успехов!

2023-05-02 16:34 UTC, merged